# Java Startup Analyzer 配置文件

# LLM模型配置
model: "openai"  # 支持的模型: openai, anthropic
api_key: ""      # 从环境变量 JAVA_ANALYZER_API_KEY 读取
base_url: ""     # 自定义API基础URL，留空使用默认值

# 输出配置
verbose: false   # 详细输出模式

# 分析配置
analysis:
  max_log_size: 10485760  # 最大日志文件大小 (10MB)
  timeout: 300            # 分析超时时间 (秒)
  confidence_threshold: 0.5  # 置信度阈值

# 日志解析配置
log_parser:
  extract_stack_traces: true
  extract_errors: true
  extract_metadata: true
